version: '3.10'

services:
    db:
        container_name: web_database
        image: postgres:15
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: imagecapturedb
        volumes:
        - ./infra/init/:/docker-entrypoint-initdb.d
        ports:
        - "5432:5432"

    scrap_capture:
        container_name: scrap_capture
        build:
            context: .
        depends_on:
        - db
        ports:
        - "7002:7007"