version: '3.10'

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"

  # por enquanto não é necessário
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: imagecapturedb
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"