FROM python:3.10.14

WORKDIR /ImagesCaptureApp/

RUN apt-get update && apt-get install -y \
    wget \
    curl \
    chromium \
    chromium-driver

RUN python -m ensurepip --upgrade \
    && python -m pip install --upgrade pip setuptools wheel

COPY . .
RUN pip install -r requirements.txt

VOLUME [ "./images" ]

# meu entrypoint podia ser um shell script
ENTRYPOINT [ "python" , "app.py"]
